GROUP=dev.mikepenz.paparazzi
VERSION_NAME=0.0.1-a02

POM_URL=https://github.com/mikepenz/paparazzi/
POM_SCM_URL=https://github.com/mikepenz/paparazzi/
POM_SCM_CONNECTION=scm:git:git://github.com/mikepenz/paparazzi.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/mikepenz/paparazzi.git

POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=mikepenz
POM_DEVELOPER_NAME=Mike Penz
POM_DEVELOPER_URL=https://github.com/mikepenz/

SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true
SONATYPE_AUTOMATIC_RELEASE=true

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4g

android.useAndroidX=true
# Some submodules use newer SDK levels for testing.
android.suppressUnsupportedCompileSdk=UpsideDownCakePrivacySandbox

# Signals to our own plugin that we are building within the repo.
app.cash.paparazzi.internal=true

# Dokka
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
